version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./stegano-images-web
      dockerfile: Dockerfile
    ports:
      - 80:80

  backend:
    restart: always
    container_name: backend
    build:
        context: ./server
        dockerfile: Dockerfile
    expose:
      - 5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1