version: "3"
services:
  frontend:
    container_name: frontend
    image: areklis909/stegano-images-web:0.0.3
    ports:
      - "80:80"
    links:
      - backend:backend
    networks:
      - default

  backend:
    restart: always
    container_name: backend
    image: areklis909/stegano-images-server:0.0.4
    expose:
      - "5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    networks:
      - default

networks:
  default:
