version: "3"
services:
  frontend:
    container_name: frontend
    image: areklis909/stegano-images-web:0.0.3
    ports:
      - "80:80"
    links:
      - flask:flask
    networks:
      - default

  flask:
    restart: always
    container_name: backend
    image: areklis909/stegano-images-server:0.0.4
    ports:
      - "8080:5000"
    expose:
      - "5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    networks:
      default:
        aliases:
        - backend

networks:
  default:
